version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: taskflow_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: taskflow_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    # env_file:
    #   - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: taskflow
      PORT: 8080
      JWT_SECRET: supersecretkey
    restart: always

volumes:
  postgres_data: